# Write your MySQL query statement below
SELECT 
    PRODUCT.PRODUCT_ID,
    PRODUCT.PRODUCT_NAME 
FROM 
    PRODUCT
JOIN 
    SALES 
    USING (PRODUCT_ID)
GROUP BY PRODUCT_ID
HAVING MIN(SALE_DATE) >='2019-01-01' AND MAX(SALE_DATE)  <='2019-03-31'