# Write your MySQL query statement below
WITH NOT_ONE AS (
    SELECT 
        EMPLOYEE_ID,
        COUNT(DEPARTMENT_ID) AS COUNTAS
    FROM 
        EMPLOYEE
    GROUP BY EMPLOYEE_ID
    HAVING 
        COUNTAS != 1
)
SELECT 
    EMPLOYEE_ID, 
    DEPARTMENT_ID
FROM    
    EMPLOYEE
WHERE TRUE 
    AND EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM NOT_ONE)

UNION ALL

SELECT 
    EMPLOYEE_ID, 
    DEPARTMENT_ID
FROM
    EMPLOYEE
WHERE TRUE
    AND EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM NOT_ONE)
    AND PRIMARY_FLAG = 'Y'

